update German translation
Return-To-The-Roots/languages pull request #6
Opened 2017-07-20 12:40 UTC by stefson

work in progress

2017-07-20 12:57 UTC, Flamefire commented
Could you remove the fuzzy comments when you are done please?

2017-07-20 13:59 UTC, Flow86 requested changes
und natürlich alle "fuzzy"-Zeilen raus

2017-07-20 13:59 UTC, Flow86 commented on rttr-de.po
> +msgstr "Verbündete können deine Grenzen nicht mit ihren Gebäuden verkleinern. "
hier ist ein trailing whitespace, sollte entfernt werden

2017-07-20 13:59 UTC, Flow86 commented on rttr-de.po
> +msgstr "Standardmäßig keine Münzannahme aktiviert. "
wäre nicht "Keine Münzannahme standardmäßig aktiviert." schöner?

2017-07-20 13:59 UTC, Flow86 commented on rttr-de.po
> +msgstr "Der Spähturm bietet eine weite Aussicht in unerforschtes Gebiet. "
klingt "in unerforschte Gebiete" nicht besser? oder waren das die originalen Übersetzungen?

2017-07-20 13:59 UTC, Flow86 commented on rttr-de.po
> +msgstr "Das Spiel kann erst gestartet werden wenn alle Spieler unterschiedliche Farben haben, bereit sind und alle freien Plätze geschlossen sind. "
trailing whitespace

2017-07-20 13:59 UTC, Flow86 commented on rttr-de.po
>  "dann für die Herstellung von Waffen verwendet werden kann."
"... da dann die überschüssige Kohle ..." ? und das "dann" in der zweiten Zeile raus?

2017-07-20 16:01 UTC, stefson commented on rttr-de.po
> +msgstr "Der Spähturm bietet eine weite Aussicht in unerforschtes Gebiet. "
Ist beides richtig, d.h. Geschmackssache ;-)

2017-07-20 16:03 UTC, stefson commented on rttr-de.po
>  "dann für die Herstellung von Waffen verwendet werden kann."
Kann man machen. Irgendwer dagegen?

2017-07-20 16:05 UTC, stefson commented
Can I remove the +#fuzz stuff with an editor such as gedit without breaking the file? I don't see them in poedit.

2017-07-20 23:40 UTC, Flamefire commented on rttr-de.po
> +msgstr "Standardmäßig keine Münzannahme aktiviert. "
Ja. SOnst klingt es genau andersherum

2017-07-20 23:41 UTC, Flamefire commented
Yes, just delete the lines

2017-07-22 08:29 UTC, stefson commented on rttr-de.po
> +msgstr "Standardmäßig keine Münzannahme aktiviert. "
Ich hab es auf "Münzannahme standardmäßig deaktiviert." geändert, okay?

2017-07-22 08:41 UTC, stefson commented
Für die Nachrichten über gefundenes Gold/Eisen/Kohle/Granit/Wasser, welche Variante ist am besten? 

Gold gefunden
Gold gefunden.
Gold gefunden!

2017-07-30 14:19 UTC, stefson commented
Also, ich habe alles soweit korrigiert sowie Gold/Eisen/Kohle/Granit/Wasser vereinheitlicht auf ohne Punkt oder Ausrufezeichen. Die Fuzzy lines waren von mir gesetzte Markierungen in poedit, wo mir Sachen unklar gewesen waren. Okay für euch? @Flow86 @Flamefire

2017-07-30 15:24 UTC, Spikeone commented
Habe gerade im Original nachgeschaut, korrekterweise müsste es z.B. "Kohle gefunden." lauten.

2017-07-30 17:00 UTC, stefson commented
Was steht denn bei Eisen, Gold, etc. im Original?

2017-07-30 20:07 UTC, Spikeone commented
Wie meinst du? Ich hatte nur Kohle probiert auf einem Berg

2017-07-30 20:10 UTC, stefson commented
Ich will wissen ob da im Original Eisen (Gold, Granit, Wasser) gefunden steht mit oder ohne dem Punkt. Mir im Prinzip egal ob mit oder ohne Punkt, aber sich auf eines zu einigen finde ich einfach besser.

2017-07-30 20:49 UTC, Spikeone commented
Mit einem Punkt (wie oben geschrieben) - so ist es zumindest im Originalen - also IMMER ein Punkt.

2017-08-07 12:36 UTC, stefson commented
So, ich habe jetzt bei den Nachrichten zu allen Dingen die ein Geologe finden kann einen Punkt gesetzt und noch die Beschreibung des Hafengebäudes angepasst. Gibt es noch Änderungswünsche? 🔙

2017-08-07 13:48 UTC, merged